# travis R support is not great, it is not supported on windows and on mac it
# installs from brew (slow) rather than a binary package. R from brew also
# will not install from binary CRAN packages by default. so we instead use
# a generic bash base and install packages ourselves.
language: bash

matrix:
  include:

    - os: linux
      dist: bionic
      env:
        R_VERSION: 3.6.3

    - os: linux
      dist: bionic
      env:
        R_VERSION: 4.0.2

    - os: macosx
      osx_image: xcode9.4
      env:
        R_VERSION: 3.6.3

    - os: macosx
      osx_image: xcode9.4
      env:
        R_VERSION: 4.0.2

    - os: windows
      env:
        R_VERSION: 3.6.3

    - os: windows
      env:
        R_VERSION: 4.0.2

script:
  - | #install R
    echo $TRAVIS_OS_NAME

