language: bash

matrix:
  include:

    - os: linux
      dist: bionic
      env:
        R_VERSION: 3.6.3

    - os: linux
      dist: bionic
      env:
        R_VERSION: 4.0.2

    - os: macosx
      osx_image: xcode9.4
      env:
        R_VERSION: 3.6.3

    - os: macosx
      osx_image: xcode9.4
      env:
        R_VERSION: 4.0.2

    - os: windows
      env:
        R_VERSION: 3.6.3

    - os: windows
      env:
        R_VERSION: 4.0.2

script:
  - echo "matrix test $R_VERSION"

