# build PythonEmbedInR, and deploy to S3 RAN server if conditions merit.
# at this point experimental

name: build

on:
  # we build artifacts on every push and release.
  # on release events we additionally upload the artifacts to our RAN server

  push:
  release:
    types:
      - published

env:
  DEVELOPER_DIR: /Applications/Xcode_10.3.app

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15]

    steps:
      - name: print-env
        run: |
          brew unlink openssl
          brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/8b9d6d688f483a0f33fcfc93d433de501b9c3513/Formula/openssl.rb
          echo $(grep -i darwin_extsn /usr/local/Cellar/openssl/1.0.2t/lib/libcrypto.1.0.0.dylib)
          #find /usr | grep "libcrypt"
          #find /usr | grep "libssl" 
          #          echo $(otool -L '/usr/local/lib/libintl.8.dylib')
          #          echo $(otool -L '/usr/local/Cellar/gettext/0.21/lib/libintl.8.dylib') 

