# build PythonEmbedInR, and deploy to S3 RAN server if conditions merit.
# at this point experimental

name: build

on:

  push:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-10.15]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        shell: bash
        run: |
          echo "install.packages(c('PythonEmbedInR', 'synapser'), repos=c('http://cran.fhcrc.org', 'http://ran.synapse.org'))" >> installPkgs.R
          echo "library(synapser)" >> installPkgs.R
          echo "sessionInfo()" >> installPkgs.R

          R --vanilla < installPkgs.R
 
